### ISSUE TITLE
docker-compose up fails on bundle install

### ISSUE THREAD

**Issue by tstrass** [siteadmin/inferno#179]
`docker-compose up` fails at the `bundle install` step. Here is the full output:
```
Creating network "inferno_default" with the default driver
Building ruby_server
Step 1/4 : FROM ruby:2.5
2.5: Pulling from library/ruby
e79bb959ec00: Pull complete
d4b7902036fe: Pull complete
1b2a72d4e030: Pull complete
d54db43011fd: Pull complete
69d473365bb3: Pull complete
84ed2a0dc034: Pull complete
1f97f190db1e: Pull complete
761e711814b0: Pull complete
Digest: sha256:063f661153e37b60c8345c63d76c02ba914f54e0df9f6de48e7111d49d1b2828
Status: Downloaded newer image for ruby:2.5
 ---> e86557c9a8ab
Step 2/4 : COPY Gemfile* ./
 ---> bab7a6522fd0
Step 3/4 : RUN bundle install
 ---> Running in 05d607c314cf

[!] There was an error parsing `Gemfile`: There are no gemspecs at /. Bundler cannot continue.

 #  from /Gemfile:6
 #  -------------------------------------------
 #
 >  gemspec
 #
 #  -------------------------------------------
ERROR: Service 'ruby_server' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 15
```

Testing this on Windows and Ubuntu yielded the same results. Testing this on latest `master` and `v2.0.0` also yielded the same results.

**Comment by adunsulag** [comment]
I noticed the 2.0.0 and master seemed to be on the same so I went back to this commit: 854cbccf143867815b5c59d205c6aba4775a4c3d from April 3rd and that seems to build. Haven't had time to dig deeper.

**Comment by tstrass** [comment]
Ah my bad did not notice that master and 2.0.0 were on the same commit. I just tried the 854cbcc and `v1.0.6`. Both of those failed for me as well, but with a different error. Instead I get:
```
Fetching source index from https://rubygems.org/
...
Bundler::HTTPError Could not fetch specs from https://rubygems.org/
```
Not sure if there's something I need to do differently with my docker configuration, but other containers I'm using that fetch dependencies from the internet are working.

**Comment by adunsulag** [comment]
@tstrass Did you destroy the docker images completely by doing a docker-compose down -v?  I did that to start from fresh.  Also I would try pinging rubygems.org from your local machine and make sure you have network access to that website.  Maybe you have a weird firewall configuration.

**Comment by tstrass** [comment]
Yeah I removed all containers and images from the previous attempts, but no luck. And yeah I can reach rubygems.org.

**Comment by powriej** [comment]
FWIW I had the same issue. I restated docker on my system and got past the connection error with rubgems.

**Comment by powriej** [comment]
Additonally, with the docker restart 1.0.6 was able to compose up. With the 2.0.0 version I am getting the gemspec error

 Step 1/4 : FROM ruby:2.5
 ---> 1dfe66cd651f
Step 2/4 : COPY Gemfile* ./
 ---> Using cache
 ---> df0dcbbd5568
Step 3/4 : RUN bundle install
 ---> Running in 7435f82d5e72

[!] There was an error parsing `Gemfile`: There are no gemspecs at /. Bundler cannot continue.

 #  from /Gemfile:6
 #  -------------------------------------------
 #  
 >  gemspec
 #  
 #  -------------------------------------------

**Comment by arscan** [comment]
Thanks for the report!

This issue is a result of an update we made to add a bit more flexibility to how you can reuse Inferno.  I think we merged this into master a bit prematurely, as fixing this issue is turning out to be more complicated than I'd like, so I'm going to revert it for now.   We will likely incorporate this functionality into the next major version, once it is a bit more mature.

Also, I'll look into adding Docker tests so that we don't inadvertently break the Docker option.

I'll update this ticket once this is fixed.

**Comment by arscan** [comment]
In looking a little closer, there are 2 issues at play here.  The first is the one that I'm working on fixing (`[!] There was an error parsing Gemfile: There are no gemspecs at /.`). 

The second issue (`Bundler::HTTPError Could not fetch specs from https://rubygems.org/`) appears to be a firewall issue for @tstrass.  The 854cbcc commit should work.  We can discuss offline @tstrass as that is a MITRE-specific thing.

**Comment by arscan** [comment]
This should be fixed in `master` now, could you give it a shot?

**Comment by tstrass** [comment]
@arscan Confirmed I no longer see the original error on master. Still running into my network error with fetching the gems, but that seems to be a me problem. Thanks.
