### ISSUE TITLE
https://inferno.healthit.gov/inferno/bOhlG3KtlKE/strict/  -- missing links

### ISSUE THREAD

**Issue by saulakravitz** [siteadmin/inferno#187]
The links mentioned are not present:

"For more information of the Conformance Statement, visit these links:

Conformance
Argonaut Conformance Requirements
SMART on FHIR Conformance
"

**Comment by czh-orz** [comment]
Hello, 

Thanks for reporting this issue. These links should be fixed in our latest build.
