### ISSUE TITLE
US Core R4 AllergyIntolerance test doesn't actually send Patient ID

### ISSUE THREAD

**Issue by js8080** [siteadmin/inferno#235]
I may be misusing the tool here but I'm just playing around with things and trying to send an R4 AllergyIntolerance request to my FHIR service. When I launch the Inferno site, I select US Core R4, enter my FHIR base URL, hit Begin, and then click "Run" under US Core R4 Allergyintolerance Tests. 

It then prompts me for a Bearer Token and Patient ID. I enter both and click Execute. 

The AllergyIntolerance-02 test fails and then when I click "Results..." it shows me the URL it hit which contains the patient parameter but no value... it just looks like this:

GET   403   https://my-base-url/**AllergyIntolerance?patient**

Shouldn't it be including the Patient ID I provided? (I realize I'm getting a 403 in my case which is my fault but I'd still expect the patient ID to be included... unless it is and just not displayed in the UI for the Inferno tool).

**Comment by arscan** [comment]
Thanks for the report Justin! This is absolutely a bug.  We will have a fix in soon.

One thing to note:  Our US Core R4 tests (and the associated R4 version of the ONC certification tests) are still under development and are changing frequently.  But we do appreciate any feedback.

**Comment by arscan** [comment]
We pulled in the fix to our master branch.  When you have a chance, could you pull down the changes on your side and restart your server to try it out?  Let me know if you have any questions on how to do that.

Thanks again for the report.

**Comment by js8080** [comment]
Works now. Thanks!
