### ISSUE TITLE
Update sinatra to version 2.0.2  

### ISSUE THREAD

**Issue by johnrsnyder** [siteadmin/inferno#6]
There is a known high severity security vulnerability detected in sinatra >= 2.0.0, < 2.0.2 defined in Gemfile.lock.
--
Gemfile.lock update suggested: sinatra ~> 2.0.2.

Reference: https://www.cybersecurity-help.cz/vdb/SB2018060501?affChecked=1

**Comment by arscan** [comment]
Fixed in #12.  To be released 8/29.

**Comment by arscan** [comment]
Update deployed.
