### ISSUE TITLE
OIDC testing should use id_token

### ISSUE THREAD

**Issue by jmandel** [siteadmin/inferno#72]
The OIDC test asks the user to paste in a token; it should use the `id_token` from the access token response (if any) by default.

**Comment by arscan** [comment]
It should be doing that, and it appears work against my HSPC sandbox instance.  Do you have an example server where this isn't working?

SLS-06 shows the following response body:
<img width="728" alt="screen shot 2018-10-02 at 10 53 47 pm" src="https://user-images.githubusercontent.com/412901/46387749-34524100-c696-11e8-9ec7-93640a824c31.png">

And this is the prompt for the OIDC test:
<img width="720" alt="screen shot 2018-10-02 at 10 54 10 pm" src="https://user-images.githubusercontent.com/412901/46387757-4207c680-c696-11e8-8cfe-1080e2784b75.png">

**Comment by jmandel** [comment]
Oh, good to know. I'm hainv this ssue with https://launch.smarthealthit.org/v/r2/sim/eyJrIjoiMSIsImoiOiIxIiwiYiI6InNtYXJ0LTEwOTg2NjcifQ/fhir

(you can use any client id you want, or visit https://launch.smarthealthit.org to configure as desired.)

**Comment by arscan** [comment]
Thanks Josh.  I have a preliminary fix in for review at #76 if you want to try it out.

This occurs because an earlier assertion within the test fails before it has a chance to save that information.  I think this speaks to a broader test granularity issue, as this type of thing may happen elsewhere.

**Comment by radamson** [comment]
Fix has been merged in.
